#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Bop.Resource", IsApplication=true)]

namespace Bop
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_in_right = global::Bop.Resource.Animation.slide_in_right;
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_out_left = global::Bop.Resource.Animation.slide_out_left;
			global::Xamarin.Auth._MobileServices.Resource.Drawable.ic_arrow_back = global::Bop.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth._MobileServices.Resource.Id.webview = global::Bop.Resource.Id.webview;
			global::Xamarin.Auth._MobileServices.Resource.Layout.activity_webview = global::Bop.Resource.Layout.activity_webview;
			global::Xamarin.Auth._MobileServices.Resource.String.ApplicationName = global::Bop.Resource.String.ApplicationName;
			global::Xamarin.Auth._MobileServices.Resource.String.Hello = global::Bop.Resource.String.Hello;
			global::Xamarin.Auth._MobileServices.Resource.String.title_activity_webview = global::Bop.Resource.String.title_activity_webview;
			global::PCLCrypto.Resource.String.ApplicationName = global::Bop.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::Bop.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int slide_in_right = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int slide_out_left = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int slideRight = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int slideUp = 2131034115;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0e0000
			public const int androidcolors = 2131623936;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010024
			public const int font = 2130772004;
			
			// aapt resource value: 0x7f01001d
			public const int fontProviderAuthority = 2130771997;
			
			// aapt resource value: 0x7f010020
			public const int fontProviderCerts = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int fontProviderFetchStrategy = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int fontProviderFetchTimeout = 2130772002;
			
			// aapt resource value: 0x7f01001e
			public const int fontProviderPackage = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int fontProviderQuery = 2130771999;
			
			// aapt resource value: 0x7f010023
			public const int fontStyle = 2130772003;
			
			// aapt resource value: 0x7f010025
			public const int fontWeight = 2130772005;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0b0000
			public const int abc_action_bar_embed_tabs = 2131427328;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f09000f
			public const int blue = 2131296271;
			
			// aapt resource value: 0x7f090017
			public const int boporange = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int common_google_signin_btn_text_dark = 2131296280;
			
			// aapt resource value: 0x7f090000
			public const int common_google_signin_btn_text_dark_default = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int common_google_signin_btn_text_dark_disabled = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int common_google_signin_btn_text_dark_focused = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int common_google_signin_btn_text_dark_pressed = 2131296259;
			
			// aapt resource value: 0x7f090019
			public const int common_google_signin_btn_text_light = 2131296281;
			
			// aapt resource value: 0x7f090004
			public const int common_google_signin_btn_text_light_default = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int common_google_signin_btn_text_light_disabled = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int common_google_signin_btn_text_light_focused = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int common_google_signin_btn_text_light_pressed = 2131296263;
			
			// aapt resource value: 0x7f09001a
			public const int common_google_signin_btn_tint = 2131296282;
			
			// aapt resource value: 0x7f090014
			public const int darkblue = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int darkgreen = 2131296278;
			
			// aapt resource value: 0x7f090015
			public const int darkpurple = 2131296277;
			
			// aapt resource value: 0x7f090011
			public const int green = 2131296273;
			
			// aapt resource value: 0x7f09000b
			public const int notification_action_color_filter = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int notification_icon_bg_color = 2131296268;
			
			// aapt resource value: 0x7f090008
			public const int notification_material_background_media_default_color = 2131296264;
			
			// aapt resource value: 0x7f090012
			public const int orange = 2131296274;
			
			// aapt resource value: 0x7f090009
			public const int primary_text_default_material_dark = 2131296265;
			
			// aapt resource value: 0x7f090010
			public const int purple = 2131296272;
			
			// aapt resource value: 0x7f090013
			public const int red = 2131296275;
			
			// aapt resource value: 0x7f09000d
			public const int ripple_material_light = 2131296269;
			
			// aapt resource value: 0x7f09000a
			public const int secondary_text_default_material_dark = 2131296266;
			
			// aapt resource value: 0x7f09000e
			public const int secondary_text_default_material_light = 2131296270;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0c0004
			public const int compat_button_inset_horizontal_material = 2131492868;
			
			// aapt resource value: 0x7f0c0005
			public const int compat_button_inset_vertical_material = 2131492869;
			
			// aapt resource value: 0x7f0c0006
			public const int compat_button_padding_horizontal_material = 2131492870;
			
			// aapt resource value: 0x7f0c0007
			public const int compat_button_padding_vertical_material = 2131492871;
			
			// aapt resource value: 0x7f0c0008
			public const int compat_control_corner_material = 2131492872;
			
			// aapt resource value: 0x7f0c0009
			public const int notification_action_icon_size = 2131492873;
			
			// aapt resource value: 0x7f0c000a
			public const int notification_action_text_size = 2131492874;
			
			// aapt resource value: 0x7f0c000b
			public const int notification_big_circle_margin = 2131492875;
			
			// aapt resource value: 0x7f0c0001
			public const int notification_content_margin_start = 2131492865;
			
			// aapt resource value: 0x7f0c000c
			public const int notification_large_icon_height = 2131492876;
			
			// aapt resource value: 0x7f0c000d
			public const int notification_large_icon_width = 2131492877;
			
			// aapt resource value: 0x7f0c0002
			public const int notification_main_column_padding_top = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int notification_media_narrow_margin = 2131492867;
			
			// aapt resource value: 0x7f0c000e
			public const int notification_right_icon_size = 2131492878;
			
			// aapt resource value: 0x7f0c0000
			public const int notification_right_side_padding_top = 2131492864;
			
			// aapt resource value: 0x7f0c000f
			public const int notification_small_icon_background_padding = 2131492879;
			
			// aapt resource value: 0x7f0c0010
			public const int notification_small_icon_size_as_large = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int notification_subtext_size = 2131492881;
			
			// aapt resource value: 0x7f0c0012
			public const int notification_top_pad = 2131492882;
			
			// aapt resource value: 0x7f0c0013
			public const int notification_top_pad_large_text = 2131492883;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bop_Logo_Black = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Bop_Logo_Black_Block = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Bop_Logo_White = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Bop_Logo_White_Block = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_obround = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int citizenpark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_full_open_on_phone = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_dark_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_dark_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_disabled = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_light_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_light_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_icon_light_normal_background = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_focused = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_dark_normal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_dark_normal_background = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_disabled = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_focused = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_light_normal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_light_normal_background = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int facebookButton = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int googleg_disabled_color_18 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int googleg_standard_color_18 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_arrow_back = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int IconBackArrow = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int IconDining = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int IconEntertainment = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int IconHeart = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int IconNature = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int IconSettings = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int IconSettingsGrey = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int IconUser = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int IconUserGrey = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ListAucklandBridge = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ListAucklandBungy = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ListAucklandMuseum = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ListAucklandZoo = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ListBCC = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ListCassetteNine = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ListCitizenPark = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ListCocos = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ListFedDeli = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ListHunuaFalls = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ListKarekareFalls = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ListKellyTarltons = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ListKitekiteFalls = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ListLaZeppa = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ListMissionBay = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ListMotat = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ListMtEden = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ListOneTreeHill = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ListOrphansKitchen = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ListParnellGardens = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ListPiha = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ListPiha2 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ListRangitotoIsland = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ListSwashbucklers = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ListViewLocation = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ListWaiheke = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int notification_action_background = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int notification_bg = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int notification_bg_low = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int notification_bg_low_normal = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int notification_bg_low_pressed = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int notification_bg_normal = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int notification_bg_normal_pressed = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int notification_icon_background = 2130837575;
			
			// aapt resource value: 0x7f02004e
			public const int notification_template_icon_bg = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int notification_template_icon_low_bg = 2130837583;
			
			// aapt resource value: 0x7f020048
			public const int notification_tile_bg = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int notify_panel_notification_icon_bg = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int signinButton = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int signupText = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int skytowerBlurred = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int uberlogosmall = 2130837581;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0d0042
			public const int action0 = 2131558466;
			
			// aapt resource value: 0x7f0d003f
			public const int action_container = 2131558463;
			
			// aapt resource value: 0x7f0d0046
			public const int action_divider = 2131558470;
			
			// aapt resource value: 0x7f0d0040
			public const int action_image = 2131558464;
			
			// aapt resource value: 0x7f0d0041
			public const int action_text = 2131558465;
			
			// aapt resource value: 0x7f0d0050
			public const int actions = 2131558480;
			
			// aapt resource value: 0x7f0d000a
			public const int adjust_height = 2131558410;
			
			// aapt resource value: 0x7f0d000b
			public const int adjust_width = 2131558411;
			
			// aapt resource value: 0x7f0d0012
			public const int async = 2131558418;
			
			// aapt resource value: 0x7f0d000f
			public const int auto = 2131558415;
			
			// aapt resource value: 0x7f0d0013
			public const int blocking = 2131558419;
			
			// aapt resource value: 0x7f0d0019
			public const int bopLogo = 2131558425;
			
			// aapt resource value: 0x7f0d0029
			public const int bottomNavbar = 2131558441;
			
			// aapt resource value: 0x7f0d0043
			public const int cancel_action = 2131558467;
			
			// aapt resource value: 0x7f0d004b
			public const int chronometer = 2131558475;
			
			// aapt resource value: 0x7f0d0010
			public const int dark = 2131558416;
			
			// aapt resource value: 0x7f0d002a
			public const int diningButton = 2131558442;
			
			// aapt resource value: 0x7f0d0039
			public const int editText1 = 2131558457;
			
			// aapt resource value: 0x7f0d003a
			public const int editText2 = 2131558458;
			
			// aapt resource value: 0x7f0d0052
			public const int end_padder = 2131558482;
			
			// aapt resource value: 0x7f0d002c
			public const int entertainmentButton = 2131558444;
			
			// aapt resource value: 0x7f0d0028
			public const int floatMapButton = 2131558440;
			
			// aapt resource value: 0x7f0d0014
			public const int forever = 2131558420;
			
			// aapt resource value: 0x7f0d003d
			public const int googlemap = 2131558461;
			
			// aapt resource value: 0x7f0d0005
			public const int hybrid = 2131558405;
			
			// aapt resource value: 0x7f0d004d
			public const int icon = 2131558477;
			
			// aapt resource value: 0x7f0d0051
			public const int icon_group = 2131558481;
			
			// aapt resource value: 0x7f0d000c
			public const int icon_only = 2131558412;
			
			// aapt resource value: 0x7f0d003b
			public const int imageButton1 = 2131558459;
			
			// aapt resource value: 0x7f0d0034
			public const int imageButton2 = 2131558452;
			
			// aapt resource value: 0x7f0d0038
			public const int imageButton3 = 2131558456;
			
			// aapt resource value: 0x7f0d002d
			public const int imageView1 = 2131558445;
			
			// aapt resource value: 0x7f0d001a
			public const int imageView2 = 2131558426;
			
			// aapt resource value: 0x7f0d004c
			public const int info = 2131558476;
			
			// aapt resource value: 0x7f0d0015
			public const int italic = 2131558421;
			
			// aapt resource value: 0x7f0d0011
			public const int light = 2131558417;
			
			// aapt resource value: 0x7f0d0000
			public const int line1 = 2131558400;
			
			// aapt resource value: 0x7f0d0001
			public const int line3 = 2131558401;
			
			// aapt resource value: 0x7f0d0017
			public const int linearLayout1 = 2131558423;
			
			// aapt resource value: 0x7f0d001e
			public const int linearLayout2 = 2131558430;
			
			// aapt resource value: 0x7f0d0033
			public const int locationSubheader = 2131558451;
			
			// aapt resource value: 0x7f0d0036
			public const int locationViewAbout = 2131558454;
			
			// aapt resource value: 0x7f0d0031
			public const int locationViewBackButton = 2131558449;
			
			// aapt resource value: 0x7f0d0032
			public const int locationViewName = 2131558450;
			
			// aapt resource value: 0x7f0d0030
			public const int mainHeader = 2131558448;
			
			// aapt resource value: 0x7f0d003e
			public const int mapBackButton = 2131558462;
			
			// aapt resource value: 0x7f0d0045
			public const int media_actions = 2131558469;
			
			// aapt resource value: 0x7f0d002b
			public const int natureButton = 2131558443;
			
			// aapt resource value: 0x7f0d0006
			public const int none = 2131558406;
			
			// aapt resource value: 0x7f0d0007
			public const int normal = 2131558407;
			
			// aapt resource value: 0x7f0d004f
			public const int notification_background = 2131558479;
			
			// aapt resource value: 0x7f0d0048
			public const int notification_main_column = 2131558472;
			
			// aapt resource value: 0x7f0d0047
			public const int notification_main_column_container = 2131558471;
			
			// aapt resource value: 0x7f0d002f
			public const int profileButton = 2131558447;
			
			// aapt resource value: 0x7f0d001c
			public const int relativeLayout1 = 2131558428;
			
			// aapt resource value: 0x7f0d004e
			public const int right_icon = 2131558478;
			
			// aapt resource value: 0x7f0d0049
			public const int right_side = 2131558473;
			
			// aapt resource value: 0x7f0d0008
			public const int satellite = 2131558408;
			
			// aapt resource value: 0x7f0d001d
			public const int scrollView1 = 2131558429;
			
			// aapt resource value: 0x7f0d001b
			public const int searchView = 2131558427;
			
			// aapt resource value: 0x7f0d002e
			public const int settingsButton = 2131558446;
			
			// aapt resource value: 0x7f0d003c
			public const int space1 = 2131558460;
			
			// aapt resource value: 0x7f0d000d
			public const int standard = 2131558413;
			
			// aapt resource value: 0x7f0d0044
			public const int status_bar_latest_event_content = 2131558468;
			
			// aapt resource value: 0x7f0d0009
			public const int terrain = 2131558409;
			
			// aapt resource value: 0x7f0d001f
			public const int test1 = 2131558431;
			
			// aapt resource value: 0x7f0d0020
			public const int test2 = 2131558432;
			
			// aapt resource value: 0x7f0d0021
			public const int test3 = 2131558433;
			
			// aapt resource value: 0x7f0d0022
			public const int test4 = 2131558434;
			
			// aapt resource value: 0x7f0d0023
			public const int test5 = 2131558435;
			
			// aapt resource value: 0x7f0d0024
			public const int test6 = 2131558436;
			
			// aapt resource value: 0x7f0d0025
			public const int test7 = 2131558437;
			
			// aapt resource value: 0x7f0d0026
			public const int test8 = 2131558438;
			
			// aapt resource value: 0x7f0d0027
			public const int test9 = 2131558439;
			
			// aapt resource value: 0x7f0d0002
			public const int text = 2131558402;
			
			// aapt resource value: 0x7f0d0003
			public const int text2 = 2131558403;
			
			// aapt resource value: 0x7f0d0037
			public const int textView1 = 2131558455;
			
			// aapt resource value: 0x7f0d0035
			public const int textView2 = 2131558453;
			
			// aapt resource value: 0x7f0d004a
			public const int time = 2131558474;
			
			// aapt resource value: 0x7f0d0004
			public const int title = 2131558404;
			
			// aapt resource value: 0x7f0d0018
			public const int toolbar1 = 2131558424;
			
			// aapt resource value: 0x7f0d0016
			public const int webview = 2131558422;
			
			// aapt resource value: 0x7f0d000e
			public const int wide = 2131558414;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070001
			public const int cancel_button_image_alpha = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int status_bar_notification_info_maxnum = 2131165186;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_webview = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int listView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int locationView = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int loginView = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int mapView = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_action = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_action_tombstone = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_media_action = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int notification_media_cancel_action = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int notification_template_big_media = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int notification_template_big_media_custom = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int notification_template_big_media_narrow = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_template_big_media_narrow_custom = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int notification_template_custom_big = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int notification_template_icon_group = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int notification_template_lines_media = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int notification_template_media = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int notification_template_media_custom = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int notification_template_part_chronometer = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int notification_template_part_time = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int sign_in_popup = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int sign_up_popup = 2130968597;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int style_json = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080013
			public const int ApplicationName = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int Hello = 2131230738;
			
			// aapt resource value: 0x7f080015
			public const int app_name = 2131230741;
			
			// aapt resource value: 0x7f080001
			public const int common_google_play_services_enable_button = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int common_google_play_services_enable_text = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int common_google_play_services_enable_title = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int common_google_play_services_install_button = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int common_google_play_services_install_text = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int common_google_play_services_install_title = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int common_google_play_services_notification_ticker = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int common_google_play_services_unknown_issue = 2131230720;
			
			// aapt resource value: 0x7f080008
			public const int common_google_play_services_unsupported_text = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int common_google_play_services_update_button = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int common_google_play_services_update_text = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int common_google_play_services_update_title = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int common_google_play_services_updating_text = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int common_google_play_services_wear_update_text = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int common_open_on_phone = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int common_signin_button_text = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int common_signin_button_text_long = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int status_bar_notification_info_overflow = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int title_activity_webview = 2131230740;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0005
			public const int TextAppearance_Compat_Notification = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int TextAppearance_Compat_Notification_Info = 2131361798;
			
			// aapt resource value: 0x7f0a0000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131361792;
			
			// aapt resource value: 0x7f0a000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131361803;
			
			// aapt resource value: 0x7f0a0004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131361796;
			
			// aapt resource value: 0x7f0a0001
			public const int TextAppearance_Compat_Notification_Media = 2131361793;
			
			// aapt resource value: 0x7f0a0007
			public const int TextAppearance_Compat_Notification_Time = 2131361799;
			
			// aapt resource value: 0x7f0a0002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131361794;
			
			// aapt resource value: 0x7f0a0008
			public const int TextAppearance_Compat_Notification_Title = 2131361800;
			
			// aapt resource value: 0x7f0a0003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131361795;
			
			// aapt resource value: 0x7f0a0009
			public const int Widget_Compat_NotificationActionContainer = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int Widget_Compat_NotificationActionText = 2131361802;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130772003,
					2130772004,
					2130772005};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
