#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Bop.Resource", IsApplication=true)]

namespace Bop
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_in_right = global::Bop.Resource.Animation.slide_in_right;
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_out_left = global::Bop.Resource.Animation.slide_out_left;
			global::Xamarin.Auth._MobileServices.Resource.Drawable.ic_arrow_back = global::Bop.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth._MobileServices.Resource.Id.webview = global::Bop.Resource.Id.webview;
			global::Xamarin.Auth._MobileServices.Resource.Layout.activity_webview = global::Bop.Resource.Layout.activity_webview;
			global::Xamarin.Auth._MobileServices.Resource.String.ApplicationName = global::Bop.Resource.String.ApplicationName;
			global::Xamarin.Auth._MobileServices.Resource.String.Hello = global::Bop.Resource.String.Hello;
			global::Xamarin.Auth._MobileServices.Resource.String.title_activity_webview = global::Bop.Resource.String.title_activity_webview;
			global::PCLCrypto.Resource.String.ApplicationName = global::Bop.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::Bop.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int slide_in_right = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int slide_out_left = 2131034113;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0a0000
			public const int androidcolors = 2131361792;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090008
			public const int blue = 2131296264;
			
			// aapt resource value: 0x7f090010
			public const int boporange = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int common_google_signin_btn_text_dark = 2131296273;
			
			// aapt resource value: 0x7f090000
			public const int common_google_signin_btn_text_dark_default = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int common_google_signin_btn_text_dark_disabled = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int common_google_signin_btn_text_dark_focused = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int common_google_signin_btn_text_dark_pressed = 2131296259;
			
			// aapt resource value: 0x7f090012
			public const int common_google_signin_btn_text_light = 2131296274;
			
			// aapt resource value: 0x7f090004
			public const int common_google_signin_btn_text_light_default = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int common_google_signin_btn_text_light_disabled = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int common_google_signin_btn_text_light_focused = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int common_google_signin_btn_text_light_pressed = 2131296263;
			
			// aapt resource value: 0x7f090013
			public const int common_google_signin_btn_tint = 2131296275;
			
			// aapt resource value: 0x7f09000d
			public const int darkblue = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int darkgreen = 2131296271;
			
			// aapt resource value: 0x7f09000e
			public const int darkpurple = 2131296270;
			
			// aapt resource value: 0x7f09000a
			public const int green = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int orange = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int purple = 2131296265;
			
			// aapt resource value: 0x7f09000c
			public const int red = 2131296268;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BopLogo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BopLogoFancy = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int citizenpark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_full_open_on_phone = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_focused = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_disabled = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_normal_background = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_focused = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_normal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_normal_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_focused = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_normal = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_normal_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int googleg_disabled_color_18 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int googleg_standard_color_18 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_arrow_back = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int IconBackArrow = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int IconDining = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int IconEntertainment = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int IconHeart = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int IconNature = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int IconSettings = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int IconSettingsGrey = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int IconUser = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int IconUserGrey = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ListAucklandBungy = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ListAucklandZoo = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ListBCC = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ListCassetteNine = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ListCitizenPark = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int uberlogosmall = 2130837543;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0005
			public const int adjust_height = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int adjust_width = 2131427334;
			
			// aapt resource value: 0x7f0b000a
			public const int auto = 2131427338;
			
			// aapt resource value: 0x7f0b0020
			public const int bottomNavbar = 2131427360;
			
			// aapt resource value: 0x7f0b000b
			public const int dark = 2131427339;
			
			// aapt resource value: 0x7f0b0021
			public const int diningButton = 2131427361;
			
			// aapt resource value: 0x7f0b0023
			public const int entertainmentButton = 2131427363;
			
			// aapt resource value: 0x7f0b001f
			public const int floatMapButton = 2131427359;
			
			// aapt resource value: 0x7f0b002f
			public const int googlemap = 2131427375;
			
			// aapt resource value: 0x7f0b0000
			public const int hybrid = 2131427328;
			
			// aapt resource value: 0x7f0b0007
			public const int icon_only = 2131427335;
			
			// aapt resource value: 0x7f0b0028
			public const int imageButton1 = 2131427368;
			
			// aapt resource value: 0x7f0b002b
			public const int imageButton2 = 2131427371;
			
			// aapt resource value: 0x7f0b002e
			public const int imageButton3 = 2131427374;
			
			// aapt resource value: 0x7f0b0024
			public const int imageView1 = 2131427364;
			
			// aapt resource value: 0x7f0b0011
			public const int imageView2 = 2131427345;
			
			// aapt resource value: 0x7f0b0010
			public const int imageView3 = 2131427344;
			
			// aapt resource value: 0x7f0b000c
			public const int light = 2131427340;
			
			// aapt resource value: 0x7f0b000e
			public const int linearLayout1 = 2131427342;
			
			// aapt resource value: 0x7f0b0015
			public const int linearLayout2 = 2131427349;
			
			// aapt resource value: 0x7f0b0029
			public const int locationHeader = 2131427369;
			
			// aapt resource value: 0x7f0b002a
			public const int locationSubheader = 2131427370;
			
			// aapt resource value: 0x7f0b0027
			public const int mainHeader = 2131427367;
			
			// aapt resource value: 0x7f0b0030
			public const int mapBackButton = 2131427376;
			
			// aapt resource value: 0x7f0b0022
			public const int natureButton = 2131427362;
			
			// aapt resource value: 0x7f0b0001
			public const int none = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int normal = 2131427330;
			
			// aapt resource value: 0x7f0b0026
			public const int profileButton = 2131427366;
			
			// aapt resource value: 0x7f0b0013
			public const int relativeLayout1 = 2131427347;
			
			// aapt resource value: 0x7f0b0003
			public const int satellite = 2131427331;
			
			// aapt resource value: 0x7f0b0014
			public const int scrollView1 = 2131427348;
			
			// aapt resource value: 0x7f0b0012
			public const int searchView1 = 2131427346;
			
			// aapt resource value: 0x7f0b0025
			public const int settingsButton = 2131427365;
			
			// aapt resource value: 0x7f0b0008
			public const int standard = 2131427336;
			
			// aapt resource value: 0x7f0b0004
			public const int terrain = 2131427332;
			
			// aapt resource value: 0x7f0b0016
			public const int test1 = 2131427350;
			
			// aapt resource value: 0x7f0b0017
			public const int test2 = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public const int test3 = 2131427352;
			
			// aapt resource value: 0x7f0b0019
			public const int test4 = 2131427353;
			
			// aapt resource value: 0x7f0b001a
			public const int test5 = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public const int test6 = 2131427355;
			
			// aapt resource value: 0x7f0b001c
			public const int test7 = 2131427356;
			
			// aapt resource value: 0x7f0b001d
			public const int test8 = 2131427357;
			
			// aapt resource value: 0x7f0b001e
			public const int test9 = 2131427358;
			
			// aapt resource value: 0x7f0b002d
			public const int textView1 = 2131427373;
			
			// aapt resource value: 0x7f0b002c
			public const int textView2 = 2131427372;
			
			// aapt resource value: 0x7f0b000f
			public const int toolbar1 = 2131427343;
			
			// aapt resource value: 0x7f0b000d
			public const int webview = 2131427341;
			
			// aapt resource value: 0x7f0b0009
			public const int wide = 2131427337;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_webview = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ListView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int LocationView = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Map = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int style_json = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080012
			public const int ApplicationName = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int Hello = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int app_name = 2131230740;
			
			// aapt resource value: 0x7f080001
			public const int common_google_play_services_enable_button = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int common_google_play_services_enable_text = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int common_google_play_services_enable_title = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int common_google_play_services_install_button = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int common_google_play_services_install_text = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int common_google_play_services_install_title = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int common_google_play_services_notification_ticker = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int common_google_play_services_unknown_issue = 2131230720;
			
			// aapt resource value: 0x7f080008
			public const int common_google_play_services_unsupported_text = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int common_google_play_services_update_button = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int common_google_play_services_update_text = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int common_google_play_services_update_title = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int common_google_play_services_updating_text = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int common_google_play_services_wear_update_text = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int common_open_on_phone = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int common_signin_button_text = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int common_signin_button_text_long = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int title_activity_webview = 2131230739;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
